# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87b364f0b29db86b120caafdae053979c0e717d845e6be37b1d7e49e0ce363cf5b4691a762356fefe56a3822c3acc54c53b4a81cebac6cdd9b6f3d89f087bf62

test:
  secret_key_base: 71a54e49ac124933b2daf404480accdc2d12910e6dc3420baa374cdd5a71d49a5c85d893997eeab40bdc4ae2f76bd905b2923af98af46e51ff74e49abfa40651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
